// <auto-generated />
namespace PayrollMVC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Employee_Salary_Details : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Employee_Salary_Details));
        
        string IMigrationMetadata.Id
        {
            get { return "201709120850164_Employee_Salary_Details"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
